version: '3'
services:
  frontend: 
    build: ./frontend 
    ports: 
      - "3000:3000" 
    container_name: frontend-docker
    restart: always 
    links:
      - backend
  backend:
    build: ./backend
    ports:
      - "3100:3100"
    depends_on:
      - db
    networks:
      - backend
    environment:
      - MYSQL_HOST=database-docker
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DB=SensorInfo
    volumes:
      - ./www/:/var/www/html/
    container_name: backend-docker
    restart: always
    links:
      - db
  db:
    image: mysql:5.7
    networks:
      - backend
    environment:
    - MYSQL_DATABASE=SensorInfo
    - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

    container_name: database-docker
    restart: always

networks:
  backend:
    driver: bridge
