version: '3'
services:
  frontend: 
    build: ./frontend 
    ports: 
      - "3000:3000" 
    container_name: frontend-docker
    restart: always 
    links:
      - backend
  db:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=SensorInfo

    ports:
      - "3306:3306"
    container_name: database-docker
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  backend:
    build: ./backend
    ports:
      - "3100:3100"
    depends_on:
      - db
    networks:
      - backend
    environment:
      - MYSQL_HOST=database-docker
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_DB=SensorInfo
    volumes:
      - ./www/:/var/www/html/
    container_name: backend-docker
    restart: on-failure
    links:
      - db
networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local 
